sonar.projectKey=CIPOLFLO_cipolflo-web
sonar.organization=cipolflo

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=cipolflo-web
#sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/*.spec.ts,**/*.test.ts,node_modules/**,coverage/**,dist/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts

sonar.sourceEncoding=UTF-8

sonar.javascript.lcov.reportPaths=coverage/CIPOLFLO-FrontEnd/lcov.info
